spring:
  cloud:
    gateway:
      routes:
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/v1/questions/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: useranswer-service
          uri: lb://useranswer-service
          predicates:
            - Path=/api/v1/user-answers/**
        - id: interview-service
          uri: lb://interview-service
          predicates:
            - Path=/api/v1/interviews/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true